### ISSUE TITLE
Commit: A snapshot, not differences

### ISSUE THREAD

**Issue by artyom-poptsov** [shkir/GitUnderstanding#1]
Hello,

I was confused by the "Commit" chapter of the document -- it says that "[a] single commit is a set of patches" while [the official Git book says](https://www.git-scm.com/book/en/v2/Getting-Started-Git-Basics#Snapshots,-Not-Differences) that "[e]very time you commit, or save the state of your project in Git, it basically takes a picture of what all your files look like at that moment and stores a reference to that snapshot. [...] Git thinks about its data more like a stream of snapshots."

I suppose this part of the chapter should be rewritten as follows: "A commit is a snapshot of all the files in a repository.  For efficiency reasons Git stores in the snapshot only those files that were changed (that is, were in the "staging" area at the time of the commit); files that weren't changed are stored as links to previous versions."

WDYT?

-- Artyom

**Comment by shkir** [comment]
Hi Artyom,

Thanks for your comment. 

Yes, the official book says a lot about all the possible things in Git. Yes, it could be viewed as a stream of snapshots. But it doesn't help with understanding of some aspects of working with Git. IMO, thinking about commit as a set of differences of every file compared to the previous state solves some of the common problems. Good example could be a rebase process.

I want to keep that manual as short as possible, and as I mentioned in the text already, it could be not very precise technically at times, but some assumptions could help with understanding of processes. The main idea of that thing is to provide a slightly different point of view on the processes.

I'll look forward into adding something like "could be thought" where applicable. 

Feel free to add more proposals.

Thanks,
Shkir
